outputs:
  current_version:
    value: ${{ steps.get_current_version.outputs.current_version }}
  target_version:
    value: ${{ steps.next_target_version.outputs.result }}
runs:
  using: "composite"
  steps:
    # jqでpackage.jsonから現在のバージョンを取得
    - name: Get current version
      run: |
        jq -r '.version' package.json
        echo "current_version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
      id: get_current_version
      shell: bash
    # current_versionを加工してtarget_versionを取得
    - name: Get target version
      uses: actions/script@v7
      env:
        CURRENT_VERSION: ${{ steps.get_current_version.outputs.current_version }}
      with:
        script: |
          return process.env.CURRENT_VERSION.split('-')[0];
        result-encoding: string
      id: next_target_version
