inputs:
  version:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    # バージョンをpackage.jsonに書き込み
    - name: Write version
      run: |
        jq '.version = "${{ inputs.version }}"' package.json > package.json.tmp && mv package.json.tmp package.json
        jq '.version = "${{ inputs.version }}"' packages/misskey-js/package.json > packages/misskey-js/package.json.tmp && mv packages/misskey-js/package.json.tmp packages/misskey-js/package.json
      shell: bash
